//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashik.Sdk.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Categories {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Categories() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Dashik.Sdk.Resources.Categories", typeof(Categories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Misc_Description {
            get {
                return ResourceManager.GetString("Misc_Description", resourceCulture);
            }
        }
        
        internal static string Accessibility_Description {
            get {
                return ResourceManager.GetString("Accessibility_Description", resourceCulture);
            }
        }
        
        internal static string ApplicationLaunchers_Description {
            get {
                return ResourceManager.GetString("ApplicationLaunchers_Description", resourceCulture);
            }
        }
        
        internal static string Clipboard_Description {
            get {
                return ResourceManager.GetString("Clipboard_Description", resourceCulture);
            }
        }
        
        internal static string DateTime_Description {
            get {
                return ResourceManager.GetString("DateTime_Description", resourceCulture);
            }
        }
        
        internal static string EnvironmentWeather_Description {
            get {
                return ResourceManager.GetString("EnvironmentWeather_Description", resourceCulture);
            }
        }
        
        internal static string FileSystem_Description {
            get {
                return ResourceManager.GetString("FileSystem_Description", resourceCulture);
            }
        }
        
        internal static string FunGames_Description {
            get {
                return ResourceManager.GetString("FunGames_Description", resourceCulture);
            }
        }
        
        internal static string Graphics_Description {
            get {
                return ResourceManager.GetString("Graphics_Description", resourceCulture);
            }
        }
        
        internal static string Language_Description {
            get {
                return ResourceManager.GetString("Language_Description", resourceCulture);
            }
        }
        
        internal static string Multimedia_Description {
            get {
                return ResourceManager.GetString("Multimedia_Description", resourceCulture);
            }
        }
        
        internal static string OnlineServices_Description {
            get {
                return ResourceManager.GetString("OnlineServices_Description", resourceCulture);
            }
        }
        
        internal static string SystemInformation_Description {
            get {
                return ResourceManager.GetString("SystemInformation_Description", resourceCulture);
            }
        }
        
        internal static string Productivity_Description {
            get {
                return ResourceManager.GetString("Productivity_Description", resourceCulture);
            }
        }
        
        internal static string SoftwareDevelopment_Description {
            get {
                return ResourceManager.GetString("SoftwareDevelopment_Description", resourceCulture);
            }
        }
        
        internal static string Utilities_Description {
            get {
                return ResourceManager.GetString("Utilities_Description", resourceCulture);
            }
        }
    }
}
